#!/usr/bin/env python3
"""Generate Prometheus file_sd targets from monitoring/aibox/devices.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INVENTORY = ROOT / "aibox" / "devices.json"
OUT = ROOT / "prometheus" / "targets"


def _labels(d: dict[str, str]) -> str:
    inner = ", ".join(f"{k}: {json.dumps(v)}" for k, v in d.items())
    return "{" + inner + "}"


def _block(target: str, labels: dict[str, str]) -> str:
    return f'- targets: ["{target}"]\n  labels: {_labels(labels)}\n'


def main() -> None:
    inv = json.loads(INVENTORY.read_text())
    api_path = inv.get("api_path", "/v1/MEGBOX/devices")
    vendor = inv.get("vendor", "megvii")
    interval = inv.get("scrape_interval", "1m")
    devices = inv["devices"]

    aibox_sd = []
    icmp_sd = []
    http_sd = []
    for dev in devices:
        name = dev["name"]
        ip = dev["ip"]
        labels = {
            "host": name,
            "ip": ip,
            "role": "aibox",
            "vendor": vendor,
        }
        url = f"http://{ip}{api_path}"
        aibox_sd.append(_block(url, labels))
        icmp_sd.append(_block(ip, {"host": name, "role": "aibox"}))
        http_sd.append(_block(url, {"host": name, "app": "megbox-api", "role": "aibox"}))

    header = (
        f"# Generated from {INVENTORY.relative_to(ROOT)} — do not edit.\n"
        f"# scrape_interval hint: {interval} (job aibox in prometheus.yml).\n"
        f"# Regenerated by: python3 scripts/gen-aibox-targets.py\n"
    )
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "aibox.yml").write_text(header + "\n" + "".join(aibox_sd))
    (OUT / "icmp-aibox.yml").write_text(header + "\n" + "".join(icmp_sd))
    (OUT / "http-aibox.yml").write_text(header + "\n" + "".join(http_sd))
    print(f"wrote {len(devices)} AI Box targets (scrape_interval={interval})")


if __name__ == "__main__":
    main()
