- targets: ["10.168.1.104"]
  labels: {vm: kong-gateway, role: guest}
- targets: ["10.168.1.55"]
  labels: {vm: faceid, role: guest}
- targets: ["10.168.1.56"]
  labels: {vm: wiseeye, role: guest}
- targets: ["10.168.1.58"]
  labels: {vm: unilever, role: guest}
- targets: ["10.168.1.59"]
  labels: {vm: chebichat, role: guest}
- targets: ["10.168.1.106"]
  labels: {vm: nx-vms, role: guest}
- targets: ["10.168.1.1"]
  labels: {vm: gateway, role: infra}
- targets: ["10.168.1.3"]
  labels: {vm: nas-backup, role: infra}
- targets: ["10.168.1.5"]
  labels: {host: gx10-b273, role: physical}
- targets: ["10.168.1.50"]
  labels: {host: GHT-Koala-01, role: physical}
- targets: ["10.168.1.51"]
  labels: {host: intel-nuc7, role: physical}
- targets: ["10.168.1.54"]
  labels: {host: ght-demo-server, role: physical}
- targets: ["192.168.3.101"]
  labels: {host: ght-dev-server, role: physical}
