- targets: ["10.168.1.104:22"]
  labels: {vm: kong-gateway, role: guest}
- targets: ["10.168.1.55:22"]
  labels: {vm: faceid, role: guest}
- targets: ["10.168.1.56:22"]
  labels: {vm: wiseeye, role: guest}
- targets: ["10.168.1.58:22"]
  labels: {vm: unilever, role: guest}
- targets: ["10.168.1.59:22"]
  labels: {vm: chebichat, role: guest}
- targets: ["10.168.1.106:22"]
  labels: {vm: nx-vms, role: guest}
- targets: ["10.168.1.5:22"]
  labels: {host: gx10-b273, role: physical}
- targets: ["10.168.1.50:22"]
  labels: {host: GHT-Koala-01, role: physical}
- targets: ["10.168.1.51:22"]
  labels: {host: intel-nuc7, role: physical}
- targets: ["10.168.1.54:22"]
  labels: {host: ght-demo-server, role: physical}
- targets: ["192.168.3.101:22"]
  labels: {host: ght-dev-server, role: physical}
