#!/bin/bash
# Script to configure static IP for ethernet interface
# Sets up netplan configuration for permanent static IP

set -e

echo "================================"
echo "Static IP Configuration"
echo "================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Configuration variables
INTERFACE="enp3s0"
STATIC_IP="192.168.3.100/24"
GATEWAY="192.168.3.1"
DNS_SERVERS="8.8.8.8,8.8.4.4"

echo ""
echo "Configuration:"
echo "  Interface: $INTERFACE"
echo "  Static IP: $STATIC_IP"
echo "  Gateway: $GATEWAY"
echo "  DNS Servers: $DNS_SERVERS"
echo ""

# Verify interface exists
if ! ip link show "$INTERFACE" &>/dev/null; then
    echo "Error: Interface $INTERFACE not found"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

# Backup existing netplan configuration
NETPLAN_DIR="/etc/netplan"
BACKUP_DIR="/etc/netplan/backup-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp -r "$NETPLAN_DIR"/*.yaml "$BACKUP_DIR"/ 2>/dev/null || true
echo "Backed up netplan config to $BACKUP_DIR"

# Remove old netplan configurations
rm -f "$NETPLAN_DIR"/*.yaml

# Create new netplan configuration with static IP
cat > "$NETPLAN_DIR/01-static-ip.yaml" << EOF
# Static IP configuration for $INTERFACE
# Generated by setup-static-ip.sh on $(date)

network:
  version: 2
  renderer: networkd
  
  ethernets:
    $INTERFACE:
      dhcp4: no
      dhcp6: no
      addresses:
        - $STATIC_IP
      routes:
        - to: default
          via: $GATEWAY
      nameservers:
        addresses: [$DNS_SERVERS]
EOF

echo ""
echo "Created netplan configuration:"
cat "$NETPLAN_DIR/01-static-ip.yaml"
echo ""

# Apply netplan configuration
echo "Applying netplan configuration..."
echo "WARNING: Network will briefly disconnect!"
read -p "Continue? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted. Configuration file created but not applied."
    echo "To apply manually, run: sudo netplan apply"
    exit 0
fi

echo "Applying in 3 seconds..."
sleep 3

netplan apply

echo ""
echo "Waiting for network to stabilize..."
sleep 5

echo ""
echo "================================"
echo "Configuration Applied!"
echo "================================"
echo ""
echo "Current IP configuration for $INTERFACE:"
ip addr show "$INTERFACE"
echo ""
echo "Testing connectivity..."
if ping -c 3 $GATEWAY &>/dev/null; then
    echo "✓ Gateway ($GATEWAY) is reachable"
else
    echo "✗ Warning: Cannot reach gateway ($GATEWAY)"
fi

if ping -c 3 8.8.8.8 &>/dev/null; then
    echo "✓ Internet connectivity OK"
else
    echo "✗ Warning: No internet connectivity"
fi

echo ""
echo "Static IP configuration complete!"
echo ""
echo "To modify the configuration, edit: $NETPLAN_DIR/01-static-ip.yaml"
echo "Then apply with: sudo netplan apply"
