#!/bin/bash
# Script to setup bridge network for KVM VMs to access physical LAN
# This allows VMs to get IP addresses from your physical network DHCP

set -e

echo "================================"
echo "Bridge Network Setup for KVM"
echo "================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

BRIDGE_NAME="br0"

# Detect primary network interface
PRIMARY_INTERFACE=$(ip route | grep default | awk '{print $5}' | head -1)

if [ -z "$PRIMARY_INTERFACE" ]; then
    echo "Error: Could not detect primary network interface"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

echo ""
echo "Detected primary interface: $PRIMARY_INTERFACE"
echo "Bridge name: $BRIDGE_NAME"
echo ""

# Check if bridge already exists
if ip link show "$BRIDGE_NAME" &>/dev/null; then
    echo "Bridge $BRIDGE_NAME already exists!"
    echo ""
    ip addr show "$BRIDGE_NAME"
    echo ""
    read -p "Do you want to recreate it? (yes/no): " RECREATE
    if [ "$RECREATE" != "yes" ]; then
        echo "Keeping existing bridge."
        exit 0
    fi
fi

# Install bridge-utils if not present
if ! command -v brctl &>/dev/null; then
    echo "Installing bridge-utils..."
    apt-get update
    apt-get install -y bridge-utils
fi

echo ""
echo "Creating netplan configuration for bridge..."

# Backup existing netplan configuration
NETPLAN_DIR="/etc/netplan"
BACKUP_DIR="/etc/netplan/backup-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp -r "$NETPLAN_DIR"/*.yaml "$BACKUP_DIR"/ 2>/dev/null || true
echo "Backed up netplan config to $BACKUP_DIR"

# Create new netplan configuration with bridge
cat > "$NETPLAN_DIR/01-netcfg.yaml" << EOF
# Bridge configuration for KVM VMs
# Generated by setup-bridge-network.sh on $(date)

network:
  version: 2
  renderer: networkd
  
  ethernets:
    $PRIMARY_INTERFACE:
      dhcp4: no
      dhcp6: no
  
  bridges:
    $BRIDGE_NAME:
      interfaces: [$PRIMARY_INTERFACE]
      dhcp4: yes
      dhcp6: no
      parameters:
        stp: false
        forward-delay: 0
EOF

echo "Created netplan configuration:"
cat "$NETPLAN_DIR/01-netcfg.yaml"
echo ""

# Apply netplan configuration
echo "Applying netplan configuration..."
echo "WARNING: Network will briefly disconnect!"
sleep 3

netplan apply

echo ""
echo "Waiting for network to stabilize..."
sleep 5

# Verify bridge is up
if ip link show "$BRIDGE_NAME" &>/dev/null; then
    echo ""
    echo "================================"
    echo "Bridge setup successful!"
    echo "================================"
    echo ""
    ip addr show "$BRIDGE_NAME"
    echo ""
    echo "Bridge interface: $BRIDGE_NAME"
    echo "Physical interface: $PRIMARY_INTERFACE"
    echo ""
    echo "Your VMs will now be able to:"
    echo "  - Get IP addresses from your physical LAN DHCP"
    echo "  - Be accessible from other devices on your network"
    echo "  - Access the internet through your gateway"
    echo ""
    echo "To create a VM using this bridge:"
    echo "  ./scripts/vm/create-faceid-vm.sh"
    echo ""
    echo "================================"
else
    echo ""
    echo "Error: Bridge creation may have failed"
    echo "Checking network status..."
    ip addr show
    echo ""
    echo "You may need to restore the backup:"
    echo "  sudo cp $BACKUP_DIR/*.yaml $NETPLAN_DIR/"
    echo "  sudo netplan apply"
    exit 1
fi

# Show routing table
echo "Current routing table:"
ip route
echo ""

# Test connectivity
echo "Testing connectivity..."
if ping -c 2 8.8.8.8 &>/dev/null; then
    echo "✓ Internet connectivity working"
else
    echo "⚠ Warning: Internet connectivity test failed"
    echo "  This might be temporary. Check your network."
fi

echo ""
echo "Setup complete! You can now create VMs that use the physical LAN."
