#!/bin/bash
# Script to configure complete network setup
# - enp3s0: Static IP configuration
# - eno1: Bridge (br0) for VM networking

set -e

echo "================================"
echo "Complete Network Configuration"
echo "================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Configuration variables
STATIC_INTERFACE="enp3s0"
STATIC_IP="192.168.3.100/24"
GATEWAY="192.168.3.1"
DNS_SERVERS="8.8.8.8,8.8.4.4"

BRIDGE_INTERFACE="eno1"
BRIDGE_NAME="br0"

echo ""
echo "Configuration:"
echo "  Static Interface: $STATIC_INTERFACE"
echo "    - IP: $STATIC_IP"
echo "    - Gateway: $GATEWAY"
echo "    - DNS: $DNS_SERVERS"
echo ""
echo "  Bridge Interface: $BRIDGE_INTERFACE -> $BRIDGE_NAME"
echo "    - DHCP enabled for bridge"
echo ""

# Verify interfaces exist
if ! ip link show "$STATIC_INTERFACE" &>/dev/null; then
    echo "Error: Interface $STATIC_INTERFACE not found"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

if ! ip link show "$BRIDGE_INTERFACE" &>/dev/null; then
    echo "Error: Interface $BRIDGE_INTERFACE not found"
    echo "Available interfaces:"
    ip link show
    exit 1
fi

# Install bridge-utils if not present
if ! command -v brctl &>/dev/null; then
    echo "Installing bridge-utils..."
    apt-get update
    apt-get install -y bridge-utils
fi

# Backup existing netplan configuration
NETPLAN_DIR="/etc/netplan"
BACKUP_DIR="/etc/netplan/backup-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp -r "$NETPLAN_DIR"/*.yaml "$BACKUP_DIR"/ 2>/dev/null || true
echo "Backed up netplan config to $BACKUP_DIR"

# Remove old netplan configurations
rm -f "$NETPLAN_DIR"/*.yaml

# Create new netplan configuration
cat > "$NETPLAN_DIR/01-network-config.yaml" << EOF
# Complete network configuration
# Generated by setup-network.sh on $(date)
#
# $STATIC_INTERFACE: Static IP for host network
# $BRIDGE_NAME: Bridge for VM networking (using $BRIDGE_INTERFACE)

network:
  version: 2
  renderer: networkd
  
  ethernets:
    $STATIC_INTERFACE:
      dhcp4: no
      dhcp6: no
      addresses:
        - $STATIC_IP
      routes:
        - to: default
          via: $GATEWAY
      nameservers:
        addresses: [$DNS_SERVERS]
    
    $BRIDGE_INTERFACE:
      dhcp4: no
      dhcp6: no
  
  bridges:
    $BRIDGE_NAME:
      interfaces: [$BRIDGE_INTERFACE]
      dhcp4: yes
      dhcp6: no
      parameters:
        stp: false
        forward-delay: 0
EOF

echo ""
echo "Created netplan configuration:"
cat "$NETPLAN_DIR/01-network-config.yaml"
echo ""

# Apply netplan configuration
echo "Applying netplan configuration..."
echo "WARNING: Network will briefly disconnect!"
read -p "Continue? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted. Configuration file created but not applied."
    echo "To apply manually, run: sudo netplan apply"
    exit 0
fi

echo "Applying in 3 seconds..."
sleep 3

netplan apply

echo ""
echo "Waiting for network to stabilize..."
sleep 5

echo ""
echo "================================"
echo "Configuration Applied!"
echo "================================"
echo ""
echo "Static interface ($STATIC_INTERFACE):"
ip addr show "$STATIC_INTERFACE"
echo ""
echo "Bridge interface ($BRIDGE_NAME):"
ip addr show "$BRIDGE_NAME"
echo ""

echo "Testing connectivity..."
if ping -c 3 $GATEWAY &>/dev/null; then
    echo "✓ Gateway ($GATEWAY) is reachable"
else
    echo "✗ Warning: Cannot reach gateway ($GATEWAY)"
fi

if ping -c 3 8.8.8.8 &>/dev/null; then
    echo "✓ Internet connectivity OK"
else
    echo "✗ Warning: No internet connectivity"
fi

echo ""
echo "Network configuration complete!"
echo ""
echo "Configuration details:"
echo "  - Static IP on $STATIC_INTERFACE: $STATIC_IP"
echo "  - Bridge $BRIDGE_NAME on $BRIDGE_INTERFACE (for VMs)"
echo ""
echo "To modify, edit: $NETPLAN_DIR/01-network-config.yaml"
echo "Then apply with: sudo netplan apply"
